development:
  TWITTER_KEY: "KZa9ECYh5ASx9SbKslUIgSfoX"
  TWITTER_SECRET: "RZWzy1oDe3zBq9CwgdSnr1mYVus6BvAQjaLgqASbG78J2ClFVL"
  FACEBOOK_KEY: "1103977139618823"
  FACEBOOK_SECRET: "749874082c12f80daea33b51f582ddac"
production:
  TWITTER_KEY: "KZa9ECYh5ASx9SbKslUIgSfoX"
  TWITTER_SECRET: "RZWzy1oDe3zBq9CwgdSnr1mYVus6BvAQjaLgqASbG78J2ClFVL"
  FACEBOOK_KEY: "1103977139618823"
  FACEBOOK_SECRET: "749874082c12f80daea33b51f582ddac"
